name: Update VOTD Authors

on:
  schedule:
    - cron: '0 0-21/3 * * *'
  workflow_dispatch:

jobs:
  update_votd_authors:
    name: Update VOTD Authors
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Convert Notebook to Script
        run: jupyter nbconvert --to script VOTD_authors.ipynb

      - name: Run Script
        run: python VOTD_authors.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add VOTD_authors.csv
          git commit -m "Updated VOTD Authors on `date` with GitHub Actions"
          git push origin master
